const path=location.pathname.toLowerCase();
const pages=[["/","Home"],["/about","About"],["/education","Education"],["/experience","Experience"],["/projects","Projects"],["/awards","Awards"]];
const active=href=>href==="/"?(path==="/"||path.endsWith("index.html")):path.startsWith(href);
const header=document.querySelector("[data-header]");
if(header){header.innerHTML=`<div class="shell nav"><a class="brand" href="/"><img src="/uploads/logo-er.png" width="34" height="34" alt=""><span>Eshaan Revankar</span></a><button class="menu-button" type="button" aria-expanded="false" aria-controls="site-menu">Menu</button><nav class="nav-links" id="site-menu" aria-label="Primary">${pages.map(([href,label])=>`<a href="${href}"${active(href)?' aria-current="page"':""}>${label}</a>`).join("")}<a class="nav-cta" href="/contact">Contact</a></nav></div>`;const button=header.querySelector(".menu-button"),menu=header.querySelector(".nav-links");button?.addEventListener("click",()=>{const open=menu.classList.toggle("open");button.setAttribute("aria-expanded",String(open))});addEventListener("scroll",()=>header.classList.toggle("scrolled",scrollY>8),{passive:true})}
const footer=document.querySelector("[data-footer]");if(footer)footer.innerHTML=`<div class="shell footer-inner"><span>© 2026 Eshaan Revankar</span><div class="footer-links"><a href="https://github.com/eshaanrev" target="_blank" rel="noopener noreferrer">GitHub</a><a href="https://www.vividsenselabs.com/" target="_blank" rel="noopener noreferrer">VividSense</a><a href="/uploads/Eshaan-Revankar-Resume.pdf" target="_blank">Résumé</a></div></div>`;
const reduceMotion=matchMedia("(prefers-reduced-motion: reduce)").matches,reveals=document.querySelectorAll(".reveal");if(reduceMotion||!("IntersectionObserver" in window))reveals.forEach(el=>el.classList.add("shown"));else{const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("shown");observer.unobserve(entry.target)}}),{rootMargin:"0px 0px -8%"});reveals.forEach(el=>observer.observe(el))}
document.querySelectorAll("[data-filter]").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll("[data-filter]").forEach(item=>item.classList.remove("active"));button.classList.add("active");const filter=button.dataset.filter;document.querySelectorAll("[data-project]").forEach(project=>{project.hidden=filter!=="all"&&project.dataset.project!==filter})}));
document.querySelectorAll("[data-tab]").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll("[data-tab]").forEach(item=>item.classList.remove("active"));document.querySelectorAll("[data-panel]").forEach(panel=>{panel.hidden=panel.dataset.panel!==button.dataset.tab});button.classList.add("active")}));
const githubStats=document.querySelector("[data-github-stats]");if(githubStats)fetch("https://api.github.com/users/eshaanrev/repos?per_page=100").then(response=>response.ok?response.json():Promise.reject()).then(repos=>{const original=repos.filter(repo=>!repo.fork),stars=original.reduce((sum,repo)=>sum+repo.stargazers_count,0);githubStats.innerHTML=`<div class="card stat"><strong>${original.length}</strong><span>Public repositories</span></div><div class="card stat"><strong>${stars}</strong><span>Stars earned</span></div><div class="card stat"><strong>4</strong><span>Live web projects</span></div><div class="card stat"><strong>2022</strong><span>Building in public since</span></div>`}).catch(()=>{});if(reduceMotion)document.querySelectorAll("video").forEach(video=>video.pause());
